---
dependency:
  name: galaxy
driver:
  name: lxd
lint:
  name: yamllint
  enabled: False
platforms:
  - name: ansible-elasticsearch-molecule
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    enabled: False
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
