---
dependency:
  name: galaxy
driver:
  name: lxd
lint:
  name: yamllint
  enabled: False
platforms:
  - name: instance
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    enabled: False
  env:
    ANSIBLE_ROLES_PATH: $HOME/.ansible/roles
    ANSIBLE_LOCAL_TEMP: $HOME/.ansible/tmp
    ANSIBLE_REMOTE_TEMP: $HOME/.ansible/tmp
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
